# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 650, 480))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.tabs.setFont(font)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setObjectName("tabs")
        self.LED_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED_1.sizePolicy().hasHeightForWidth())
        self.LED_1.setSizePolicy(sizePolicy)
        self.LED_1.setMinimumSize(QtCore.QSize(50, 0))
        self.LED_1.setObjectName("LED_1")
        self.LED_1_B = QtWidgets.QProgressBar(self.LED_1)
        self.LED_1_B.setGeometry(QtCore.QRect(110, 403, 511, 16))
        self.LED_1_B.setMaximum(255)
        self.LED_1_B.setProperty("value", 0)
        self.LED_1_B.setTextVisible(False)
        self.LED_1_B.setOrientation(QtCore.Qt.Horizontal)
        self.LED_1_B.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.LED_1_B.setFormat("")
        self.LED_1_B.setObjectName("LED_1_B")
        self.LED_1_G = QtWidgets.QProgressBar(self.LED_1)
        self.LED_1_G.setGeometry(QtCore.QRect(110, 363, 511, 16))
        self.LED_1_G.setMaximum(255)
        self.LED_1_G.setProperty("value", 0)
        self.LED_1_G.setTextVisible(False)
        self.LED_1_G.setOrientation(QtCore.Qt.Horizontal)
        self.LED_1_G.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.LED_1_G.setFormat("")
        self.LED_1_G.setObjectName("LED_1_G")
        self.LED_1_R = QtWidgets.QProgressBar(self.LED_1)
        self.LED_1_R.setGeometry(QtCore.QRect(110, 323, 511, 16))
        self.LED_1_R.setAutoFillBackground(False)
        self.LED_1_R.setStyleSheet("")
        self.LED_1_R.setMaximum(255)
        self.LED_1_R.setProperty("value", 0)
        self.LED_1_R.setTextVisible(False)
        self.LED_1_R.setOrientation(QtCore.Qt.Horizontal)
        self.LED_1_R.setInvertedAppearance(False)
        self.LED_1_R.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.LED_1_R.setFormat("")
        self.LED_1_R.setObjectName("LED_1_R")
        self.lred_1 = QtWidgets.QLabel(self.LED_1)
        self.lred_1.setGeometry(QtCore.QRect(10, 320, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lred_1.setFont(font)
        self.lred_1.setObjectName("lred_1")
        self.lgreen_1 = QtWidgets.QLabel(self.LED_1)
        self.lgreen_1.setGeometry(QtCore.QRect(10, 360, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        self.lgreen_1.setFont(font)
        self.lgreen_1.setObjectName("lgreen_1")
        self.lblue_1 = QtWidgets.QLabel(self.LED_1)
        self.lblue_1.setGeometry(QtCore.QRect(10, 400, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        self.lblue_1.setFont(font)
        self.lblue_1.setObjectName("lblue_1")
        self.splitline_1 = QtWidgets.QFrame(self.LED_1)
        self.splitline_1.setGeometry(QtCore.QRect(0, 300, 641, 20))
        self.splitline_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.splitline_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitline_1.setObjectName("splitline_1")
        self.frame = QtWidgets.QFrame(self.LED_1)
        self.frame.setGeometry(QtCore.QRect(-30, 10, 171, 291))
        self.frame.setStyleSheet("#frame {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(3)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 20, 102, 252))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pink_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pink_1.sizePolicy().hasHeightForWidth())
        self.pink_1.setSizePolicy(sizePolicy)
        self.pink_1.setMinimumSize(QtCore.QSize(50, 50))
        self.pink_1.setAutoFillBackground(False)
        self.pink_1.setStyleSheet("#pink_1 {\n"
"border:none;\n"
"background:rgb(255, 0, 153)\n"
"}")
        self.pink_1.setText("")
        self.pink_1.setAutoDefault(False)
        self.pink_1.setDefault(False)
        self.pink_1.setFlat(False)
        self.pink_1.setObjectName("pink_1")
        self.gridLayout.addWidget(self.pink_1, 4, 0, 1, 1)
        self.black_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.black_1.sizePolicy().hasHeightForWidth())
        self.black_1.setSizePolicy(sizePolicy)
        self.black_1.setMinimumSize(QtCore.QSize(50, 50))
        self.black_1.setAutoFillBackground(False)
        self.black_1.setStyleSheet("#black_1 {\n"
"border:none;\n"
"background:rgb(0, 0, 0)\n"
"}")
        self.black_1.setText("")
        self.black_1.setAutoDefault(False)
        self.black_1.setDefault(False)
        self.black_1.setFlat(False)
        self.black_1.setObjectName("black_1")
        self.gridLayout.addWidget(self.black_1, 6, 2, 1, 1)
        self.yellow_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yellow_1.sizePolicy().hasHeightForWidth())
        self.yellow_1.setSizePolicy(sizePolicy)
        self.yellow_1.setMinimumSize(QtCore.QSize(50, 50))
        self.yellow_1.setAutoFillBackground(False)
        self.yellow_1.setStyleSheet("#yellow_1 {\n"
"border:none;\n"
"background-color:rgb(255, 255, 0)\n"
"}")
        self.yellow_1.setText("")
        self.yellow_1.setAutoDefault(False)
        self.yellow_1.setDefault(False)
        self.yellow_1.setFlat(False)
        self.yellow_1.setObjectName("yellow_1")
        self.gridLayout.addWidget(self.yellow_1, 1, 2, 1, 1)
        self.purple_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.purple_1.sizePolicy().hasHeightForWidth())
        self.purple_1.setSizePolicy(sizePolicy)
        self.purple_1.setMinimumSize(QtCore.QSize(50, 50))
        self.purple_1.setAutoFillBackground(False)
        self.purple_1.setStyleSheet("#purple_1 {\n"
"border:none;\n"
"background: rgb(170, 0, 255)\n"
"}")
        self.purple_1.setText("")
        self.purple_1.setAutoDefault(False)
        self.purple_1.setDefault(False)
        self.purple_1.setFlat(False)
        self.purple_1.setObjectName("purple_1")
        self.gridLayout.addWidget(self.purple_1, 5, 0, 1, 1)
        self.red_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.red_1.sizePolicy().hasHeightForWidth())
        self.red_1.setSizePolicy(sizePolicy)
        self.red_1.setMinimumSize(QtCore.QSize(50, 50))
        self.red_1.setAutoFillBackground(False)
        self.red_1.setStyleSheet("#red_1 {\n"
"border:none;\n"
"background: rgb(255, 0, 0)\n"
"}")
        self.red_1.setText("")
        self.red_1.setAutoDefault(False)
        self.red_1.setDefault(False)
        self.red_1.setFlat(False)
        self.red_1.setObjectName("red_1")
        self.gridLayout.addWidget(self.red_1, 2, 0, 1, 1)
        self.orange_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.orange_1.setMinimumSize(QtCore.QSize(50, 50))
        self.orange_1.setAutoFillBackground(False)
        self.orange_1.setStyleSheet("#orange_1 {\n"
"border:none;\n"
"background: rgb(255, 149, 0)\n"
"}")
        self.orange_1.setText("")
        self.orange_1.setAutoDefault(False)
        self.orange_1.setDefault(False)
        self.orange_1.setFlat(False)
        self.orange_1.setObjectName("orange_1")
        self.gridLayout.addWidget(self.orange_1, 1, 0, 1, 1)
        self.white_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.white_1.sizePolicy().hasHeightForWidth())
        self.white_1.setSizePolicy(sizePolicy)
        self.white_1.setMinimumSize(QtCore.QSize(50, 50))
        self.white_1.setAutoFillBackground(False)
        self.white_1.setStyleSheet("#white_1 {\n"
"border:none;\n"
"background: rgb(255, 255, 255)\n"
"}")
        self.white_1.setText("")
        self.white_1.setAutoDefault(False)
        self.white_1.setDefault(False)
        self.white_1.setFlat(False)
        self.white_1.setObjectName("white_1")
        self.gridLayout.addWidget(self.white_1, 6, 0, 1, 1)
        self.blue_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blue_1.sizePolicy().hasHeightForWidth())
        self.blue_1.setSizePolicy(sizePolicy)
        self.blue_1.setMinimumSize(QtCore.QSize(50, 50))
        self.blue_1.setAutoFillBackground(False)
        self.blue_1.setStyleSheet("#blue_1 {\n"
"border:none;\n"
"background: rgb(0, 0, 255)\n"
"}")
        self.blue_1.setText("")
        self.blue_1.setAutoDefault(False)
        self.blue_1.setDefault(False)
        self.blue_1.setFlat(False)
        self.blue_1.setObjectName("blue_1")
        self.gridLayout.addWidget(self.blue_1, 5, 2, 1, 1)
        self.green_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.green_1.sizePolicy().hasHeightForWidth())
        self.green_1.setSizePolicy(sizePolicy)
        self.green_1.setMinimumSize(QtCore.QSize(50, 50))
        self.green_1.setAutoFillBackground(False)
        self.green_1.setStyleSheet("#green_1 {\n"
"border:none;\n"
"background:rgb(0, 255, 29)\n"
"}")
        self.green_1.setText("")
        self.green_1.setAutoDefault(False)
        self.green_1.setDefault(False)
        self.green_1.setFlat(False)
        self.green_1.setObjectName("green_1")
        self.gridLayout.addWidget(self.green_1, 2, 2, 1, 1)
        self.cyan_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cyan_1.sizePolicy().hasHeightForWidth())
        self.cyan_1.setSizePolicy(sizePolicy)
        self.cyan_1.setMinimumSize(QtCore.QSize(50, 50))
        self.cyan_1.setAutoFillBackground(False)
        self.cyan_1.setStyleSheet("#cyan_1 {\n"
"border:none;\n"
"background:rgb(0, 243, 255)\n"
"}")
        self.cyan_1.setText("")
        self.cyan_1.setAutoDefault(False)
        self.cyan_1.setDefault(False)
        self.cyan_1.setFlat(False)
        self.cyan_1.setObjectName("cyan_1")
        self.gridLayout.addWidget(self.cyan_1, 4, 2, 1, 1)
        self.red_1.raise_()
        self.purple_1.raise_()
        self.white_1.raise_()
        self.green_1.raise_()
        self.cyan_1.raise_()
        self.orange_1.raise_()
        self.pink_1.raise_()
        self.black_1.raise_()
        self.yellow_1.raise_()
        self.blue_1.raise_()
        self.color_1 = QtWidgets.QDial(self.LED_1)
        self.color_1.setGeometry(QtCore.QRect(179, 79, 211, 151))
        self.color_1.setMaximum(359)
        self.color_1.setSingleStep(1)
        self.color_1.setPageStep(60)
        self.color_1.setSliderPosition(180)
        self.color_1.setOrientation(QtCore.Qt.Horizontal)
        self.color_1.setInvertedAppearance(False)
        self.color_1.setWrapping(True)
        self.color_1.setNotchesVisible(True)
        self.color_1.setObjectName("color_1")
        self.circle_1 = QtWidgets.QGraphicsView(self.LED_1)
        self.circle_1.setGeometry(QtCore.QRect(150, 20, 271, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_1.sizePolicy().hasHeightForWidth())
        self.circle_1.setSizePolicy(sizePolicy)
        self.circle_1.setMinimumSize(QtCore.QSize(270, 270))
        self.circle_1.setAutoFillBackground(True)
        self.circle_1.setStyleSheet("#circle_1{\n"
"background : url(:/Color/color_wheel_hsl.png)\n"
"}")
        self.circle_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circle_1.setObjectName("circle_1")
        self.bright_1 = QtWidgets.QDial(self.LED_1)
        self.bright_1.setGeometry(QtCore.QRect(420, 20, 111, 91))
        self.bright_1.setMaximum(100)
        self.bright_1.setSingleStep(5)
        self.bright_1.setPageStep(20)
        self.bright_1.setTracking(True)
        self.bright_1.setOrientation(QtCore.Qt.Horizontal)
        self.bright_1.setWrapping(False)
        self.bright_1.setNotchTarget(3.7)
        self.bright_1.setNotchesVisible(True)
        self.bright_1.setObjectName("bright_1")
        self.satur_1 = QtWidgets.QDial(self.LED_1)
        self.satur_1.setGeometry(QtCore.QRect(420, 110, 111, 91))
        self.satur_1.setMaximum(100)
        self.satur_1.setSingleStep(5)
        self.satur_1.setPageStep(20)
        self.satur_1.setNotchesVisible(True)
        self.satur_1.setObjectName("satur_1")
        self.speed_1 = QtWidgets.QDial(self.LED_1)
        self.speed_1.setGeometry(QtCore.QRect(420, 200, 111, 91))
        self.speed_1.setMinimum(0)
        self.speed_1.setMaximum(100)
        self.speed_1.setSingleStep(5)
        self.speed_1.setPageStep(20)
        self.speed_1.setProperty("value", 50)
        self.speed_1.setWrapping(False)
        self.speed_1.setNotchesVisible(True)
        self.speed_1.setObjectName("speed_1")
        self.nbright_1 = QtWidgets.QLCDNumber(self.LED_1)
        self.nbright_1.setGeometry(QtCore.QRect(530, 30, 91, 51))
        self.nbright_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nbright_1.setProperty("intValue", 0)
        self.nbright_1.setObjectName("nbright_1")
        self.nsatur_1 = QtWidgets.QLCDNumber(self.LED_1)
        self.nsatur_1.setGeometry(QtCore.QRect(530, 120, 91, 51))
        self.nsatur_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nsatur_1.setObjectName("nsatur_1")
        self.lbright_1 = QtWidgets.QLabel(self.LED_1)
        self.lbright_1.setGeometry(QtCore.QRect(530, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbright_1.setFont(font)
        self.lbright_1.setObjectName("lbright_1")
        self.lsatur_1 = QtWidgets.QLabel(self.LED_1)
        self.lsatur_1.setGeometry(QtCore.QRect(530, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsatur_1.setFont(font)
        self.lsatur_1.setObjectName("lsatur_1")
        self.bpulse_1 = QtWidgets.QPushButton(self.LED_1)
        self.bpulse_1.setGeometry(QtCore.QRect(530, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bpulse_1.setFont(font)
        self.bpulse_1.setCheckable(True)
        self.bpulse_1.setObjectName("bpulse_1")
        self.bauto_1 = QtWidgets.QPushButton(self.LED_1)
        self.bauto_1.setGeometry(QtCore.QRect(530, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bauto_1.setFont(font)
        self.bauto_1.setCheckable(True)
        self.bauto_1.setFlat(False)
        self.bauto_1.setObjectName("bauto_1")
        self.LED_1_B.raise_()
        self.LED_1_G.raise_()
        self.LED_1_R.raise_()
        self.lred_1.raise_()
        self.lgreen_1.raise_()
        self.lblue_1.raise_()
        self.splitline_1.raise_()
        self.frame.raise_()
        self.circle_1.raise_()
        self.color_1.raise_()
        self.bright_1.raise_()
        self.satur_1.raise_()
        self.speed_1.raise_()
        self.nbright_1.raise_()
        self.nsatur_1.raise_()
        self.lbright_1.raise_()
        self.lsatur_1.raise_()
        self.bpulse_1.raise_()
        self.bauto_1.raise_()
        self.tabs.addTab(self.LED_1, "")
        self.LED_2 = QtWidgets.QWidget()
        self.LED_2.setObjectName("LED_2")
        self.frame_2 = QtWidgets.QFrame(self.LED_2)
        self.frame_2.setGeometry(QtCore.QRect(-30, 10, 171, 291))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(5)
        self.frame_2.setMidLineWidth(3)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 20, 102, 252))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pink_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pink_2.sizePolicy().hasHeightForWidth())
        self.pink_2.setSizePolicy(sizePolicy)
        self.pink_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pink_2.setAutoFillBackground(False)
        self.pink_2.setStyleSheet("#pink_2 {\n"
"border:none;\n"
"background:rgb(255, 0, 153)\n"
"}")
        self.pink_2.setText("")
        self.pink_2.setAutoDefault(False)
        self.pink_2.setDefault(False)
        self.pink_2.setFlat(False)
        self.pink_2.setObjectName("pink_2")
        self.gridLayout_2.addWidget(self.pink_2, 4, 0, 1, 1)
        self.black_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.black_2.sizePolicy().hasHeightForWidth())
        self.black_2.setSizePolicy(sizePolicy)
        self.black_2.setMinimumSize(QtCore.QSize(50, 50))
        self.black_2.setAutoFillBackground(False)
        self.black_2.setStyleSheet("#black_2 {\n"
"border:none;\n"
"background:rgb(0, 0, 0)\n"
"}")
        self.black_2.setText("")
        self.black_2.setAutoDefault(False)
        self.black_2.setDefault(False)
        self.black_2.setFlat(False)
        self.black_2.setObjectName("black_2")
        self.gridLayout_2.addWidget(self.black_2, 6, 2, 1, 1)
        self.yellow_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yellow_2.sizePolicy().hasHeightForWidth())
        self.yellow_2.setSizePolicy(sizePolicy)
        self.yellow_2.setMinimumSize(QtCore.QSize(50, 50))
        self.yellow_2.setAutoFillBackground(False)
        self.yellow_2.setStyleSheet("#yellow_2 {\n"
"border:none;\n"
"background-color:rgb(255, 255, 0)\n"
"}")
        self.yellow_2.setText("")
        self.yellow_2.setAutoDefault(False)
        self.yellow_2.setDefault(False)
        self.yellow_2.setFlat(False)
        self.yellow_2.setObjectName("yellow_2")
        self.gridLayout_2.addWidget(self.yellow_2, 1, 2, 1, 1)
        self.purple_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.purple_2.sizePolicy().hasHeightForWidth())
        self.purple_2.setSizePolicy(sizePolicy)
        self.purple_2.setMinimumSize(QtCore.QSize(50, 50))
        self.purple_2.setAutoFillBackground(False)
        self.purple_2.setStyleSheet("#purple_2 {\n"
"border:none;\n"
"background: rgb(170, 0, 255)\n"
"}")
        self.purple_2.setText("")
        self.purple_2.setAutoDefault(False)
        self.purple_2.setDefault(False)
        self.purple_2.setFlat(False)
        self.purple_2.setObjectName("purple_2")
        self.gridLayout_2.addWidget(self.purple_2, 5, 0, 1, 1)
        self.red_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.red_2.sizePolicy().hasHeightForWidth())
        self.red_2.setSizePolicy(sizePolicy)
        self.red_2.setMinimumSize(QtCore.QSize(50, 50))
        self.red_2.setAutoFillBackground(False)
        self.red_2.setStyleSheet("#red_2 {\n"
"border:none;\n"
"background: rgb(255, 0, 0)\n"
"}")
        self.red_2.setText("")
        self.red_2.setAutoDefault(False)
        self.red_2.setDefault(False)
        self.red_2.setFlat(False)
        self.red_2.setObjectName("red_2")
        self.gridLayout_2.addWidget(self.red_2, 2, 0, 1, 1)
        self.orange_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.orange_2.setMinimumSize(QtCore.QSize(50, 50))
        self.orange_2.setAutoFillBackground(False)
        self.orange_2.setStyleSheet("#orange_2 {\n"
"border:none;\n"
"background: rgb(255, 149, 0)\n"
"}")
        self.orange_2.setText("")
        self.orange_2.setAutoDefault(False)
        self.orange_2.setDefault(False)
        self.orange_2.setFlat(False)
        self.orange_2.setObjectName("orange_2")
        self.gridLayout_2.addWidget(self.orange_2, 1, 0, 1, 1)
        self.white_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.white_2.sizePolicy().hasHeightForWidth())
        self.white_2.setSizePolicy(sizePolicy)
        self.white_2.setMinimumSize(QtCore.QSize(50, 50))
        self.white_2.setAutoFillBackground(False)
        self.white_2.setStyleSheet("#white_2 {\n"
"border:none;\n"
"background: rgb(255, 255, 255)\n"
"}")
        self.white_2.setText("")
        self.white_2.setAutoDefault(False)
        self.white_2.setDefault(False)
        self.white_2.setFlat(False)
        self.white_2.setObjectName("white_2")
        self.gridLayout_2.addWidget(self.white_2, 6, 0, 1, 1)
        self.blue_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blue_2.sizePolicy().hasHeightForWidth())
        self.blue_2.setSizePolicy(sizePolicy)
        self.blue_2.setMinimumSize(QtCore.QSize(50, 50))
        self.blue_2.setAutoFillBackground(False)
        self.blue_2.setStyleSheet("#blue_2 {\n"
"border:none;\n"
"background: rgb(0, 0, 255)\n"
"}")
        self.blue_2.setText("")
        self.blue_2.setAutoDefault(False)
        self.blue_2.setDefault(False)
        self.blue_2.setFlat(False)
        self.blue_2.setObjectName("blue_2")
        self.gridLayout_2.addWidget(self.blue_2, 5, 2, 1, 1)
        self.green_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.green_2.sizePolicy().hasHeightForWidth())
        self.green_2.setSizePolicy(sizePolicy)
        self.green_2.setMinimumSize(QtCore.QSize(50, 50))
        self.green_2.setAutoFillBackground(False)
        self.green_2.setStyleSheet("#green_2 {\n"
"border:none;\n"
"background:rgb(0, 255, 29)\n"
"}")
        self.green_2.setText("")
        self.green_2.setAutoDefault(False)
        self.green_2.setDefault(False)
        self.green_2.setFlat(False)
        self.green_2.setObjectName("green_2")
        self.gridLayout_2.addWidget(self.green_2, 2, 2, 1, 1)
        self.cyan_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cyan_2.sizePolicy().hasHeightForWidth())
        self.cyan_2.setSizePolicy(sizePolicy)
        self.cyan_2.setMinimumSize(QtCore.QSize(50, 50))
        self.cyan_2.setAutoFillBackground(False)
        self.cyan_2.setStyleSheet("#cyan_2 {\n"
"border:none;\n"
"background:rgb(0, 243, 255)\n"
"}")
        self.cyan_2.setText("")
        self.cyan_2.setAutoDefault(False)
        self.cyan_2.setDefault(False)
        self.cyan_2.setFlat(False)
        self.cyan_2.setObjectName("cyan_2")
        self.gridLayout_2.addWidget(self.cyan_2, 4, 2, 1, 1)
        self.LED_2_G = QtWidgets.QProgressBar(self.LED_2)
        self.LED_2_G.setGeometry(QtCore.QRect(110, 363, 511, 16))
        self.LED_2_G.setMaximum(255)
        self.LED_2_G.setProperty("value", 0)
        self.LED_2_G.setTextVisible(False)
        self.LED_2_G.setOrientation(QtCore.Qt.Horizontal)
        self.LED_2_G.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.LED_2_G.setFormat("")
        self.LED_2_G.setObjectName("LED_2_G")
        self.lsatur_2 = QtWidgets.QLabel(self.LED_2)
        self.lsatur_2.setGeometry(QtCore.QRect(530, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsatur_2.setFont(font)
        self.lsatur_2.setObjectName("lsatur_2")
        self.bauto_2 = QtWidgets.QPushButton(self.LED_2)
        self.bauto_2.setGeometry(QtCore.QRect(530, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bauto_2.setFont(font)
        self.bauto_2.setCheckable(True)
        self.bauto_2.setFlat(False)
        self.bauto_2.setObjectName("bauto_2")
        self.lred_2 = QtWidgets.QLabel(self.LED_2)
        self.lred_2.setGeometry(QtCore.QRect(10, 320, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lred_2.setFont(font)
        self.lred_2.setObjectName("lred_2")
        self.circle_2 = QtWidgets.QGraphicsView(self.LED_2)
        self.circle_2.setGeometry(QtCore.QRect(150, 20, 271, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_2.sizePolicy().hasHeightForWidth())
        self.circle_2.setSizePolicy(sizePolicy)
        self.circle_2.setMinimumSize(QtCore.QSize(270, 270))
        self.circle_2.setAutoFillBackground(True)
        self.circle_2.setStyleSheet("#circle_2{\n"
"background : url(:/Color/color_wheel_hsl.png)\n"
"}")
        self.circle_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circle_2.setObjectName("circle_2")
        self.nsatur_2 = QtWidgets.QLCDNumber(self.LED_2)
        self.nsatur_2.setGeometry(QtCore.QRect(530, 120, 91, 51))
        self.nsatur_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nsatur_2.setObjectName("nsatur_2")
        self.LED_2_R = QtWidgets.QProgressBar(self.LED_2)
        self.LED_2_R.setGeometry(QtCore.QRect(110, 323, 511, 16))
        self.LED_2_R.setAutoFillBackground(False)
        self.LED_2_R.setStyleSheet("")
        self.LED_2_R.setMaximum(255)
        self.LED_2_R.setProperty("value", 0)
        self.LED_2_R.setTextVisible(False)
        self.LED_2_R.setOrientation(QtCore.Qt.Horizontal)
        self.LED_2_R.setInvertedAppearance(False)
        self.LED_2_R.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.LED_2_R.setFormat("")
        self.LED_2_R.setObjectName("LED_2_R")
        self.lgreen_2 = QtWidgets.QLabel(self.LED_2)
        self.lgreen_2.setGeometry(QtCore.QRect(10, 360, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        self.lgreen_2.setFont(font)
        self.lgreen_2.setObjectName("lgreen_2")
        self.LED_2_B = QtWidgets.QProgressBar(self.LED_2)
        self.LED_2_B.setGeometry(QtCore.QRect(110, 403, 511, 16))
        self.LED_2_B.setMaximum(255)
        self.LED_2_B.setProperty("value", 0)
        self.LED_2_B.setTextVisible(False)
        self.LED_2_B.setOrientation(QtCore.Qt.Horizontal)
        self.LED_2_B.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.LED_2_B.setFormat("")
        self.LED_2_B.setObjectName("LED_2_B")
        self.lblue_2 = QtWidgets.QLabel(self.LED_2)
        self.lblue_2.setGeometry(QtCore.QRect(10, 400, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        self.lblue_2.setFont(font)
        self.lblue_2.setObjectName("lblue_2")
        self.nbright_2 = QtWidgets.QLCDNumber(self.LED_2)
        self.nbright_2.setGeometry(QtCore.QRect(530, 30, 91, 51))
        self.nbright_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nbright_2.setProperty("intValue", 0)
        self.nbright_2.setObjectName("nbright_2")
        self.color_2 = QtWidgets.QDial(self.LED_2)
        self.color_2.setGeometry(QtCore.QRect(179, 79, 211, 151))
        self.color_2.setMaximum(359)
        self.color_2.setSingleStep(1)
        self.color_2.setPageStep(60)
        self.color_2.setSliderPosition(180)
        self.color_2.setOrientation(QtCore.Qt.Horizontal)
        self.color_2.setInvertedAppearance(False)
        self.color_2.setWrapping(True)
        self.color_2.setNotchesVisible(True)
        self.color_2.setObjectName("color_2")
        self.lbright_2 = QtWidgets.QLabel(self.LED_2)
        self.lbright_2.setGeometry(QtCore.QRect(530, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbright_2.setFont(font)
        self.lbright_2.setObjectName("lbright_2")
        self.speed_2 = QtWidgets.QDial(self.LED_2)
        self.speed_2.setGeometry(QtCore.QRect(420, 200, 111, 91))
        self.speed_2.setMinimum(0)
        self.speed_2.setMaximum(100)
        self.speed_2.setSingleStep(5)
        self.speed_2.setPageStep(20)
        self.speed_2.setProperty("value", 50)
        self.speed_2.setWrapping(False)
        self.speed_2.setNotchesVisible(True)
        self.speed_2.setObjectName("speed_2")
        self.satur_2 = QtWidgets.QDial(self.LED_2)
        self.satur_2.setGeometry(QtCore.QRect(420, 110, 111, 91))
        self.satur_2.setMaximum(100)
        self.satur_2.setSingleStep(5)
        self.satur_2.setPageStep(20)
        self.satur_2.setNotchesVisible(True)
        self.satur_2.setObjectName("satur_2")
        self.splitline_2 = QtWidgets.QFrame(self.LED_2)
        self.splitline_2.setGeometry(QtCore.QRect(0, 300, 641, 20))
        self.splitline_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.splitline_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitline_2.setObjectName("splitline_2")
        self.bpulse_2 = QtWidgets.QPushButton(self.LED_2)
        self.bpulse_2.setGeometry(QtCore.QRect(530, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bpulse_2.setFont(font)
        self.bpulse_2.setCheckable(True)
        self.bpulse_2.setObjectName("bpulse_2")
        self.bright_2 = QtWidgets.QDial(self.LED_2)
        self.bright_2.setGeometry(QtCore.QRect(420, 20, 111, 91))
        self.bright_2.setMaximum(100)
        self.bright_2.setSingleStep(5)
        self.bright_2.setPageStep(20)
        self.bright_2.setTracking(True)
        self.bright_2.setOrientation(QtCore.Qt.Horizontal)
        self.bright_2.setWrapping(False)
        self.bright_2.setNotchTarget(3.7)
        self.bright_2.setNotchesVisible(True)
        self.bright_2.setObjectName("bright_2")
        self.tabs.addTab(self.LED_2, "")
        self.LED3 = QtWidgets.QWidget()
        self.LED3.setObjectName("LED3")
        self.LED_3_G = QtWidgets.QProgressBar(self.LED3)
        self.LED_3_G.setGeometry(QtCore.QRect(110, 363, 511, 16))
        self.LED_3_G.setMaximum(255)
        self.LED_3_G.setProperty("value", 0)
        self.LED_3_G.setTextVisible(False)
        self.LED_3_G.setOrientation(QtCore.Qt.Horizontal)
        self.LED_3_G.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.LED_3_G.setFormat("")
        self.LED_3_G.setObjectName("LED_3_G")
        self.bauto_3 = QtWidgets.QPushButton(self.LED3)
        self.bauto_3.setGeometry(QtCore.QRect(530, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bauto_3.setFont(font)
        self.bauto_3.setCheckable(True)
        self.bauto_3.setFlat(False)
        self.bauto_3.setObjectName("bauto_3")
        self.lsatur_3 = QtWidgets.QLabel(self.LED3)
        self.lsatur_3.setGeometry(QtCore.QRect(530, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lsatur_3.setFont(font)
        self.lsatur_3.setObjectName("lsatur_3")
        self.circle_3 = QtWidgets.QGraphicsView(self.LED3)
        self.circle_3.setGeometry(QtCore.QRect(150, 20, 271, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_3.sizePolicy().hasHeightForWidth())
        self.circle_3.setSizePolicy(sizePolicy)
        self.circle_3.setMinimumSize(QtCore.QSize(270, 270))
        self.circle_3.setAutoFillBackground(True)
        self.circle_3.setStyleSheet("#circle_3{\n"
"background : url(:/Color/color_wheel_hsl.png)\n"
"}")
        self.circle_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circle_3.setObjectName("circle_3")
        self.frame_3 = QtWidgets.QFrame(self.LED3)
        self.frame_3.setGeometry(QtCore.QRect(-30, 10, 171, 291))
        self.frame_3.setStyleSheet("#frame_3 {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 20px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(5)
        self.frame_3.setMidLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(50, 20, 102, 252))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pink_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pink_3.sizePolicy().hasHeightForWidth())
        self.pink_3.setSizePolicy(sizePolicy)
        self.pink_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pink_3.setAutoFillBackground(False)
        self.pink_3.setStyleSheet("#pink_3 {\n"
"border:none;\n"
"background:rgb(255, 0, 153)\n"
"}")
        self.pink_3.setText("")
        self.pink_3.setAutoDefault(False)
        self.pink_3.setDefault(False)
        self.pink_3.setFlat(False)
        self.pink_3.setObjectName("pink_3")
        self.gridLayout_3.addWidget(self.pink_3, 4, 0, 1, 1)
        self.black_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.black_3.sizePolicy().hasHeightForWidth())
        self.black_3.setSizePolicy(sizePolicy)
        self.black_3.setMinimumSize(QtCore.QSize(50, 50))
        self.black_3.setAutoFillBackground(False)
        self.black_3.setStyleSheet("#black_3 {\n"
"border:none;\n"
"background:rgb(0, 0, 0)\n"
"}")
        self.black_3.setText("")
        self.black_3.setAutoDefault(False)
        self.black_3.setDefault(False)
        self.black_3.setFlat(False)
        self.black_3.setObjectName("black_3")
        self.gridLayout_3.addWidget(self.black_3, 6, 2, 1, 1)
        self.yellow_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yellow_3.sizePolicy().hasHeightForWidth())
        self.yellow_3.setSizePolicy(sizePolicy)
        self.yellow_3.setMinimumSize(QtCore.QSize(50, 50))
        self.yellow_3.setAutoFillBackground(False)
        self.yellow_3.setStyleSheet("#yellow_3 {\n"
"border:none;\n"
"background-color:rgb(255, 255, 0)\n"
"}")
        self.yellow_3.setText("")
        self.yellow_3.setAutoDefault(False)
        self.yellow_3.setDefault(False)
        self.yellow_3.setFlat(False)
        self.yellow_3.setObjectName("yellow_3")
        self.gridLayout_3.addWidget(self.yellow_3, 1, 2, 1, 1)
        self.purple_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.purple_3.sizePolicy().hasHeightForWidth())
        self.purple_3.setSizePolicy(sizePolicy)
        self.purple_3.setMinimumSize(QtCore.QSize(50, 50))
        self.purple_3.setAutoFillBackground(False)
        self.purple_3.setStyleSheet("#purple_3 {\n"
"border:none;\n"
"background: rgb(170, 0, 255)\n"
"}")
        self.purple_3.setText("")
        self.purple_3.setAutoDefault(False)
        self.purple_3.setDefault(False)
        self.purple_3.setFlat(False)
        self.purple_3.setObjectName("purple_3")
        self.gridLayout_3.addWidget(self.purple_3, 5, 0, 1, 1)
        self.red_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.red_3.sizePolicy().hasHeightForWidth())
        self.red_3.setSizePolicy(sizePolicy)
        self.red_3.setMinimumSize(QtCore.QSize(50, 50))
        self.red_3.setAutoFillBackground(False)
        self.red_3.setStyleSheet("#red_3 {\n"
"border:none;\n"
"background: rgb(255, 0, 0)\n"
"}")
        self.red_3.setText("")
        self.red_3.setAutoDefault(False)
        self.red_3.setDefault(False)
        self.red_3.setFlat(False)
        self.red_3.setObjectName("red_3")
        self.gridLayout_3.addWidget(self.red_3, 2, 0, 1, 1)
        self.orange_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.orange_3.setMinimumSize(QtCore.QSize(50, 50))
        self.orange_3.setAutoFillBackground(False)
        self.orange_3.setStyleSheet("#orange_3 {\n"
"border:none;\n"
"background: rgb(255, 149, 0)\n"
"}")
        self.orange_3.setText("")
        self.orange_3.setAutoDefault(False)
        self.orange_3.setDefault(False)
        self.orange_3.setFlat(False)
        self.orange_3.setObjectName("orange_3")
        self.gridLayout_3.addWidget(self.orange_3, 1, 0, 1, 1)
        self.white_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.white_3.sizePolicy().hasHeightForWidth())
        self.white_3.setSizePolicy(sizePolicy)
        self.white_3.setMinimumSize(QtCore.QSize(50, 50))
        self.white_3.setAutoFillBackground(False)
        self.white_3.setStyleSheet("#white_3 {\n"
"border:none;\n"
"background: rgb(255, 255, 255)\n"
"}")
        self.white_3.setText("")
        self.white_3.setAutoDefault(False)
        self.white_3.setDefault(False)
        self.white_3.setFlat(False)
        self.white_3.setObjectName("white_3")
        self.gridLayout_3.addWidget(self.white_3, 6, 0, 1, 1)
        self.blue_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blue_3.sizePolicy().hasHeightForWidth())
        self.blue_3.setSizePolicy(sizePolicy)
        self.blue_3.setMinimumSize(QtCore.QSize(50, 50))
        self.blue_3.setAutoFillBackground(False)
        self.blue_3.setStyleSheet("#blue_3 {\n"
"border:none;\n"
"background: rgb(0, 0, 255)\n"
"}")
        self.blue_3.setText("")
        self.blue_3.setAutoDefault(False)
        self.blue_3.setDefault(False)
        self.blue_3.setFlat(False)
        self.blue_3.setObjectName("blue_3")
        self.gridLayout_3.addWidget(self.blue_3, 5, 2, 1, 1)
        self.green_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.green_3.sizePolicy().hasHeightForWidth())
        self.green_3.setSizePolicy(sizePolicy)
        self.green_3.setMinimumSize(QtCore.QSize(50, 50))
        self.green_3.setAutoFillBackground(False)
        self.green_3.setStyleSheet("#green_3 {\n"
"border:none;\n"
"background:rgb(0, 255, 29)\n"
"}")
        self.green_3.setText("")
        self.green_3.setAutoDefault(False)
        self.green_3.setDefault(False)
        self.green_3.setFlat(False)
        self.green_3.setObjectName("green_3")
        self.gridLayout_3.addWidget(self.green_3, 2, 2, 1, 1)
        self.cyan_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cyan_3.sizePolicy().hasHeightForWidth())
        self.cyan_3.setSizePolicy(sizePolicy)
        self.cyan_3.setMinimumSize(QtCore.QSize(50, 50))
        self.cyan_3.setAutoFillBackground(False)
        self.cyan_3.setStyleSheet("#cyan_3 {\n"
"border:none;\n"
"background:rgb(0, 243, 255)\n"
"}")
        self.cyan_3.setText("")
        self.cyan_3.setAutoDefault(False)
        self.cyan_3.setDefault(False)
        self.cyan_3.setFlat(False)
        self.cyan_3.setObjectName("cyan_3")
        self.gridLayout_3.addWidget(self.cyan_3, 4, 2, 1, 1)
        self.lred_3 = QtWidgets.QLabel(self.LED3)
        self.lred_3.setGeometry(QtCore.QRect(10, 320, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lred_3.setFont(font)
        self.lred_3.setObjectName("lred_3")
        self.nsatur_3 = QtWidgets.QLCDNumber(self.LED3)
        self.nsatur_3.setGeometry(QtCore.QRect(530, 120, 91, 51))
        self.nsatur_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nsatur_3.setObjectName("nsatur_3")
        self.LED_3_R = QtWidgets.QProgressBar(self.LED3)
        self.LED_3_R.setGeometry(QtCore.QRect(110, 323, 511, 16))
        self.LED_3_R.setAutoFillBackground(False)
        self.LED_3_R.setStyleSheet("")
        self.LED_3_R.setMaximum(255)
        self.LED_3_R.setProperty("value", 0)
        self.LED_3_R.setTextVisible(False)
        self.LED_3_R.setOrientation(QtCore.Qt.Horizontal)
        self.LED_3_R.setInvertedAppearance(False)
        self.LED_3_R.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.LED_3_R.setFormat("")
        self.LED_3_R.setObjectName("LED_3_R")
        self.lgreen_3 = QtWidgets.QLabel(self.LED3)
        self.lgreen_3.setGeometry(QtCore.QRect(10, 360, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        self.lgreen_3.setFont(font)
        self.lgreen_3.setObjectName("lgreen_3")
        self.LED_3_B = QtWidgets.QProgressBar(self.LED3)
        self.LED_3_B.setGeometry(QtCore.QRect(110, 403, 511, 16))
        self.LED_3_B.setMaximum(255)
        self.LED_3_B.setProperty("value", 0)
        self.LED_3_B.setTextVisible(False)
        self.LED_3_B.setOrientation(QtCore.Qt.Horizontal)
        self.LED_3_B.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.LED_3_B.setFormat("")
        self.LED_3_B.setObjectName("LED_3_B")
        self.lblue_3 = QtWidgets.QLabel(self.LED3)
        self.lblue_3.setGeometry(QtCore.QRect(10, 400, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tunga")
        self.lblue_3.setFont(font)
        self.lblue_3.setObjectName("lblue_3")
        self.nbright_3 = QtWidgets.QLCDNumber(self.LED3)
        self.nbright_3.setGeometry(QtCore.QRect(530, 30, 91, 51))
        self.nbright_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nbright_3.setProperty("intValue", 0)
        self.nbright_3.setObjectName("nbright_3")
        self.color_3 = QtWidgets.QDial(self.LED3)
        self.color_3.setGeometry(QtCore.QRect(179, 79, 211, 151))
        self.color_3.setMaximum(359)
        self.color_3.setSingleStep(1)
        self.color_3.setPageStep(60)
        self.color_3.setSliderPosition(180)
        self.color_3.setOrientation(QtCore.Qt.Horizontal)
        self.color_3.setInvertedAppearance(False)
        self.color_3.setWrapping(True)
        self.color_3.setNotchesVisible(True)
        self.color_3.setObjectName("color_3")
        self.lbright_3 = QtWidgets.QLabel(self.LED3)
        self.lbright_3.setGeometry(QtCore.QRect(530, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbright_3.setFont(font)
        self.lbright_3.setObjectName("lbright_3")
        self.satur_3 = QtWidgets.QDial(self.LED3)
        self.satur_3.setGeometry(QtCore.QRect(420, 110, 111, 91))
        self.satur_3.setMaximum(100)
        self.satur_3.setSingleStep(5)
        self.satur_3.setPageStep(20)
        self.satur_3.setNotchesVisible(True)
        self.satur_3.setObjectName("satur_3")
        self.speed_3 = QtWidgets.QDial(self.LED3)
        self.speed_3.setGeometry(QtCore.QRect(420, 200, 111, 91))
        self.speed_3.setMinimum(0)
        self.speed_3.setMaximum(100)
        self.speed_3.setSingleStep(5)
        self.speed_3.setPageStep(20)
        self.speed_3.setProperty("value", 50)
        self.speed_3.setWrapping(False)
        self.speed_3.setNotchesVisible(True)
        self.speed_3.setObjectName("speed_3")
        self.splitline_3 = QtWidgets.QFrame(self.LED3)
        self.splitline_3.setGeometry(QtCore.QRect(0, 300, 641, 20))
        self.splitline_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.splitline_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitline_3.setObjectName("splitline_3")
        self.bpulse_3 = QtWidgets.QPushButton(self.LED3)
        self.bpulse_3.setGeometry(QtCore.QRect(530, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bpulse_3.setFont(font)
        self.bpulse_3.setCheckable(True)
        self.bpulse_3.setObjectName("bpulse_3")
        self.bright_3 = QtWidgets.QDial(self.LED3)
        self.bright_3.setGeometry(QtCore.QRect(420, 20, 111, 91))
        self.bright_3.setMaximum(100)
        self.bright_3.setSingleStep(5)
        self.bright_3.setPageStep(20)
        self.bright_3.setTracking(True)
        self.bright_3.setOrientation(QtCore.Qt.Horizontal)
        self.bright_3.setWrapping(False)
        self.bright_3.setNotchTarget(3.7)
        self.bright_3.setNotchesVisible(True)
        self.bright_3.setObjectName("bright_3")
        self.tabs.addTab(self.LED3, "")
        self.time = QtWidgets.QWidget()
        self.time.setObjectName("time")
        self.frame_time = QtWidgets.QFrame(self.time)
        self.frame_time.setGeometry(QtCore.QRect(30, 30, 581, 321))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(24)
        self.frame_time.setFont(font)
        self.frame_time.setStyleSheet("#frame_time \n"
"{\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 20px;\n"
"}")
        self.frame_time.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_time.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_time.setObjectName("frame_time")
        self.mon_time = QtWidgets.QTimeEdit(self.frame_time)
        self.mon_time.setGeometry(QtCore.QRect(40, 20, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.mon_time.setFont(font)
        self.mon_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mon_time.setAutoFillBackground(False)
        self.mon_time.setWrapping(True)
        self.mon_time.setFrame(False)
        self.mon_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.mon_time.setAccelerated(True)
        self.mon_time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.mon_time.setTime(QtCore.QTime(6, 0, 0))
        self.mon_time.setObjectName("mon_time")
        self.tue_time = QtWidgets.QTimeEdit(self.frame_time)
        self.tue_time.setGeometry(QtCore.QRect(230, 20, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.tue_time.setFont(font)
        self.tue_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tue_time.setAutoFillBackground(False)
        self.tue_time.setWrapping(True)
        self.tue_time.setFrame(False)
        self.tue_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.tue_time.setAccelerated(True)
        self.tue_time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.tue_time.setTime(QtCore.QTime(8, 0, 0))
        self.tue_time.setObjectName("tue_time")
        self.wed_time = QtWidgets.QTimeEdit(self.frame_time)
        self.wed_time.setGeometry(QtCore.QRect(420, 20, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.wed_time.setFont(font)
        self.wed_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wed_time.setAutoFillBackground(False)
        self.wed_time.setWrapping(True)
        self.wed_time.setFrame(False)
        self.wed_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.wed_time.setAccelerated(True)
        self.wed_time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.wed_time.setTime(QtCore.QTime(8, 0, 0))
        self.wed_time.setObjectName("wed_time")
        self.fri_time = QtWidgets.QTimeEdit(self.frame_time)
        self.fri_time.setGeometry(QtCore.QRect(230, 240, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.fri_time.setFont(font)
        self.fri_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fri_time.setAutoFillBackground(False)
        self.fri_time.setWrapping(True)
        self.fri_time.setFrame(False)
        self.fri_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.fri_time.setAccelerated(True)
        self.fri_time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.fri_time.setTime(QtCore.QTime(6, 0, 0))
        self.fri_time.setObjectName("fri_time")
        self.thu_time = QtWidgets.QTimeEdit(self.frame_time)
        self.thu_time.setGeometry(QtCore.QRect(40, 240, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.thu_time.setFont(font)
        self.thu_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thu_time.setAutoFillBackground(False)
        self.thu_time.setWrapping(True)
        self.thu_time.setFrame(False)
        self.thu_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.thu_time.setAccelerated(True)
        self.thu_time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.thu_time.setTime(QtCore.QTime(8, 0, 0))
        self.thu_time.setObjectName("thu_time")
        self.wee_time = QtWidgets.QTimeEdit(self.frame_time)
        self.wee_time.setGeometry(QtCore.QRect(420, 240, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.wee_time.setFont(font)
        self.wee_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wee_time.setAutoFillBackground(False)
        self.wee_time.setWrapping(True)
        self.wee_time.setFrame(False)
        self.wee_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.wee_time.setAccelerated(True)
        self.wee_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(10, 0, 0)))
        self.wee_time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.wee_time.setTime(QtCore.QTime(10, 0, 0))
        self.wee_time.setObjectName("wee_time")
        self.bmon = QtWidgets.QPushButton(self.frame_time)
        self.bmon.setGeometry(QtCore.QRect(40, 90, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        self.bmon.setFont(font)
        self.bmon.setCheckable(True)
        self.bmon.setObjectName("bmon")
        self.btue = QtWidgets.QPushButton(self.frame_time)
        self.btue.setGeometry(QtCore.QRect(230, 90, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        self.btue.setFont(font)
        self.btue.setCheckable(True)
        self.btue.setObjectName("btue")
        self.bwed = QtWidgets.QPushButton(self.frame_time)
        self.bwed.setGeometry(QtCore.QRect(420, 90, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        self.bwed.setFont(font)
        self.bwed.setCheckable(True)
        self.bwed.setObjectName("bwed")
        self.bthu = QtWidgets.QPushButton(self.frame_time)
        self.bthu.setGeometry(QtCore.QRect(40, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        self.bthu.setFont(font)
        self.bthu.setCheckable(True)
        self.bthu.setObjectName("bthu")
        self.bfri = QtWidgets.QPushButton(self.frame_time)
        self.bfri.setGeometry(QtCore.QRect(230, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        self.bfri.setFont(font)
        self.bfri.setCheckable(True)
        self.bfri.setObjectName("bfri")
        self.bwee = QtWidgets.QPushButton(self.frame_time)
        self.bwee.setGeometry(QtCore.QRect(420, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(18)
        self.bwee.setFont(font)
        self.bwee.setCheckable(True)
        self.bwee.setObjectName("bwee")
        self.line_4 = QtWidgets.QFrame(self.frame_time)
        self.line_4.setGeometry(QtCore.QRect(0, 145, 581, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_2 = QtWidgets.QFrame(self.time)
        self.line_2.setGeometry(QtCore.QRect(0, 370, 241, 51))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.off_time = QtWidgets.QTimeEdit(self.time)
        self.off_time.setGeometry(QtCore.QRect(250, 370, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.off_time.setFont(font)
        self.off_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.off_time.setAutoFillBackground(False)
        self.off_time.setWrapping(True)
        self.off_time.setFrame(True)
        self.off_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.off_time.setAccelerated(True)
        self.off_time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.off_time.setTime(QtCore.QTime(23, 0, 0))
        self.off_time.setObjectName("off_time")
        self.line_3 = QtWidgets.QFrame(self.time)
        self.line_3.setGeometry(QtCore.QRect(420, 370, 221, 51))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tabs.addTab(self.time, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(660, 10, 131, 471))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.fastcontroll = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.fastcontroll.setContentsMargins(0, 0, 0, 0)
        self.fastcontroll.setObjectName("fastcontroll")
        self.ntime = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ntime.sizePolicy().hasHeightForWidth())
        self.ntime.setSizePolicy(sizePolicy)
        self.ntime.setMinimumSize(QtCore.QSize(0, 50))
        self.ntime.setSmallDecimalPoint(False)
        self.ntime.setDigitCount(5)
        self.ntime.setMode(QtWidgets.QLCDNumber.Dec)
        self.ntime.setProperty("value", 1000.0)
        self.ntime.setProperty("intValue", 1000)
        self.ntime.setObjectName("ntime")
        self.fastcontroll.addWidget(self.ntime)
        self.exit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.exit.sizePolicy().hasHeightForWidth())
        self.exit.setSizePolicy(sizePolicy)
        self.exit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setDefault(False)
        self.exit.setFlat(False)
        self.exit.setObjectName("exit")
        self.fastcontroll.addWidget(self.exit)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.fastcontroll.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Miriam")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.fastcontroll.addWidget(self.label)
        self.auto_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.auto_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.auto_2.setFont(font)
        self.auto_2.setCheckable(False)
        self.auto_2.setObjectName("auto_2")
        self.fastcontroll.addWidget(self.auto_2)
        self.lon = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.lon.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.lon.setFont(font)
        self.lon.setCheckable(False)
        self.lon.setChecked(False)
        self.lon.setObjectName("lon")
        self.fastcontroll.addWidget(self.lon)
        self.loff = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loff.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.loff.setFont(font)
        self.loff.setObjectName("loff")
        self.fastcontroll.addWidget(self.loff)
        self.snooze = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.snooze.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.snooze.setFont(font)
        self.snooze.setCheckable(True)
        self.snooze.setChecked(True)
        self.snooze.setObjectName("snooze")
        self.fastcontroll.addWidget(self.snooze)
        self.line_5 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setLineWidth(3)
        self.line_5.setMidLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.fastcontroll.addWidget(self.line_5)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Miriam")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.fastcontroll.addWidget(self.label_2)
        self.pc = QtWidgets.QHBoxLayout()
        self.pc.setObjectName("pc")
        self.pc_act = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pc_act.setMinimumSize(QtCore.QSize(50, 50))
        self.pc_act.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.pc_act.setFont(font)
        self.pc_act.setCheckable(True)
        self.pc_act.setChecked(True)
        self.pc_act.setObjectName("pc_act")
        self.pc.addWidget(self.pc_act)
        self.fastcontroll.addLayout(self.pc)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lred_1.setText(_translate("MainWindow", "RED"))
        self.lgreen_1.setText(_translate("MainWindow", "GREEN"))
        self.lblue_1.setText(_translate("MainWindow", "BLUE"))
        self.lbright_1.setText(_translate("MainWindow", "Brightness"))
        self.lsatur_1.setText(_translate("MainWindow", "Saturation"))
        self.bpulse_1.setText(_translate("MainWindow", "Pulse"))
        self.bauto_1.setText(_translate("MainWindow", "Auto"))
        self.tabs.setTabText(self.tabs.indexOf(self.LED_1), _translate("MainWindow", "LED I"))
        self.lsatur_2.setText(_translate("MainWindow", "Saturation"))
        self.bauto_2.setText(_translate("MainWindow", "Auto"))
        self.lred_2.setText(_translate("MainWindow", "RED"))
        self.lgreen_2.setText(_translate("MainWindow", "GREEN"))
        self.lblue_2.setText(_translate("MainWindow", "BLUE"))
        self.lbright_2.setText(_translate("MainWindow", "Brightness"))
        self.bpulse_2.setText(_translate("MainWindow", "Pulse"))
        self.tabs.setTabText(self.tabs.indexOf(self.LED_2), _translate("MainWindow", "LED II"))
        self.bauto_3.setText(_translate("MainWindow", "Auto"))
        self.lsatur_3.setText(_translate("MainWindow", "Saturation"))
        self.lred_3.setText(_translate("MainWindow", "RED"))
        self.lgreen_3.setText(_translate("MainWindow", "GREEN"))
        self.lblue_3.setText(_translate("MainWindow", "BLUE"))
        self.lbright_3.setText(_translate("MainWindow", "Brightness"))
        self.bpulse_3.setText(_translate("MainWindow", "Pulse"))
        self.tabs.setTabText(self.tabs.indexOf(self.LED3), _translate("MainWindow", "LED III"))
        self.mon_time.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.tue_time.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.wed_time.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.fri_time.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.thu_time.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.wee_time.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.bmon.setText(_translate("MainWindow", "Monday"))
        self.btue.setText(_translate("MainWindow", "Tuesday"))
        self.bwed.setText(_translate("MainWindow", "Wednesday"))
        self.bthu.setText(_translate("MainWindow", "Thursday"))
        self.bfri.setText(_translate("MainWindow", "Friday"))
        self.bwee.setText(_translate("MainWindow", "Weekend"))
        self.off_time.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.tabs.setTabText(self.tabs.indexOf(self.time), _translate("MainWindow", "Alarm"))
        self.exit.setText(_translate("MainWindow", "EXIT"))
        self.label.setText(_translate("MainWindow", "Synced "))
        self.auto_2.setText(_translate("MainWindow", "Automatic"))
        self.lon.setText(_translate("MainWindow", "Lights on"))
        self.loff.setText(_translate("MainWindow", "Lights off"))
        self.snooze.setText(_translate("MainWindow", "Snooze"))
        self.label_2.setText(_translate("MainWindow", "PC auto OFF"))
        self.pc_act.setText(_translate("MainWindow", "Active"))

import colorcircle